from datetime import datetime
from typing import List, Dict, Any
import json

SEVERITY_ORDER = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}
SEVERITY_COLORS = {
    "CRITICAL": "#FF0000",
    "HIGH": "#FF6600",
    "MEDIUM": "#FFB800",
    "LOW": "#4CAF50",
    "INFO": "#2196F3",
}

def generate_markdown_report(scan_data: Dict) -> str:
    """Generate a comprehensive markdown bug bounty report."""
    target = scan_data.get("target", "Unknown")
    timestamp = scan_data.get("timestamp", datetime.utcnow().isoformat())
    all_findings = scan_data.get("all_findings", [])

    # Sort by severity
    all_findings = sorted(all_findings, key=lambda x: SEVERITY_ORDER.get(x.get("severity", "INFO"), 99))

    # Count by severity
    counts = {}
    for f in all_findings:
        sev = f.get("severity", "INFO")
        counts[sev] = counts.get(sev, 0) + 1

    report = f"""# Bug Bounty Penetration Test Report

**Target:** `{target}`  
**Date:** {timestamp}  
**Report Generated By:** Bug Bounty Hunter Platform v1.0  
**Classification:** CONFIDENTIAL

---

## Executive Summary

A comprehensive security assessment was performed against `{target}`. The assessment covered subdomain enumeration, port scanning, directory fuzzing, parameter discovery, web application vulnerabilities (XSS, SQLi, SSRF/XXE), API security, cloud infrastructure, and network security headers.

### Findings Summary

| Severity | Count |
|----------|-------|
| 🔴 Critical | {counts.get('CRITICAL', 0)} |
| 🟠 High | {counts.get('HIGH', 0)} |
| 🟡 Medium | {counts.get('MEDIUM', 0)} |
| 🟢 Low | {counts.get('LOW', 0)} |
| 🔵 Info | {counts.get('INFO', 0)} |
| **Total** | **{len(all_findings)}** |

### Overall Risk Rating

"""
    if counts.get("CRITICAL", 0) > 0:
        report += "**🔴 CRITICAL** - Immediate action required. Critical vulnerabilities found that could lead to full system compromise.\n"
    elif counts.get("HIGH", 0) > 0:
        report += "**🟠 HIGH** - High-severity vulnerabilities require prompt remediation.\n"
    elif counts.get("MEDIUM", 0) > 0:
        report += "**🟡 MEDIUM** - Medium-severity vulnerabilities should be addressed in the near term.\n"
    else:
        report += "**🟢 LOW** - No critical or high severity issues found. Continue monitoring.\n"

    report += "\n---\n\n## Detailed Findings\n\n"

    for i, finding in enumerate(all_findings, 1):
        severity = finding.get("severity", "INFO")
        finding_type = finding.get("type", "Unknown")
        url = finding.get("url", target)
        param = finding.get("param", "N/A")
        payload = finding.get("payload", "N/A")
        evidence = finding.get("evidence", "N/A")
        cvss = finding.get("cvss", "N/A")
        remediation = finding.get("remediation", "See OWASP guidelines")

        severity_emoji = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🟢", "INFO": "🔵"}.get(severity, "⚪")

        report += f"""### Finding #{i}: {finding_type}

**Severity:** {severity_emoji} {severity}  
**CVSS Score:** {cvss}  
**URL:** `{url}`  
**Parameter:** `{param}`  

#### Evidence
```
{evidence}
```

#### Payload Used
```
{payload}
```

#### Remediation
{remediation}

---

"""

    # Recon summary
    report += "\n## Recon Summary\n\n"

    if "subdomains" in scan_data:
        subs = scan_data["subdomains"]
        report += f"### Subdomains Discovered ({len(subs)})\n\n"
        takeover = [s for s in subs if s.get("takeover_possible")]
        if takeover:
            report += f"⚠️ **{len(takeover)} potential subdomain takeover(s) detected:**\n"
            for s in takeover:
                report += f"- `{s['subdomain']}` → CNAME: `{s.get('cname', 'N/A')}`\n"
        report += "\n"

    if "open_ports" in scan_data:
        ports = scan_data["open_ports"]
        report += f"### Open Ports ({len(ports)})\n\n"
        report += "| Port | Service | State | Risky |\n|------|---------|-------|-------|\n"
        for p in ports:
            risky = "⚠️ YES" if p.get("risky") else "No"
            report += f"| {p['port']} | {p.get('service', 'Unknown')} | {p.get('state', 'open')} | {risky} |\n"
        report += "\n"

    report += """## Methodology

1. **Reconnaissance** - Passive and active recon including subdomain enumeration via crt.sh and DNS brute-forcing
2. **Port Scanning** - TCP connect scan on common and well-known ports
3. **Directory Fuzzing** - Content discovery using curated wordlists
4. **Parameter Discovery** - HTML form parsing and common parameter testing
5. **Vulnerability Assessment** - XSS, SQLi, SSRF/XXE testing across discovered attack surface
6. **API Security Testing** - REST/GraphQL endpoint discovery, BOLA, and data exposure testing
7. **Cloud Security** - S3/Azure/GCP bucket enumeration, Firebase database checks
8. **Network Security** - HTTP security headers, CORS, SSL/TLS certificate analysis

## Tools & Techniques

- Custom Python-based scanners
- DNS resolver (dnspython)
- Certificate Transparency (crt.sh)
- HTTP proxy-based parameter testing
- OWASP Top 10 vulnerability checks

## Disclaimer

This report was generated for authorized security testing purposes only. All testing was conducted against systems where explicit permission was granted. The findings in this report should be treated as confidential and used solely for remediation purposes.

---
*Report generated by Bug Bounty Hunter Platform*
"""
    return report

def calculate_risk_score(all_findings: List[Dict]) -> float:
    """Calculate an overall risk score 0-10."""
    weights = {"CRITICAL": 10, "HIGH": 7, "MEDIUM": 4, "LOW": 2, "INFO": 0.5}
    if not all_findings:
        return 0.0
    total = sum(weights.get(f.get("severity", "INFO"), 0) for f in all_findings)
    max_possible = len(all_findings) * 10
    return round(min(10.0, (total / max_possible) * 10), 1) if max_possible > 0 else 0.0

def get_findings_by_severity(all_findings: List[Dict]) -> Dict:
    """Group findings by severity."""
    grouped = {"CRITICAL": [], "HIGH": [], "MEDIUM": [], "LOW": [], "INFO": []}
    for f in all_findings:
        sev = f.get("severity", "INFO")
        grouped.setdefault(sev, []).append(f)
    return grouped
